baseURL: 'https://jaysqvl.github.io/'
languageCode: "en-us"
title: "Jay Esquivel Jr."
theme: ["hugo-embed-pdf-shortcode", "hugo-profile"]
enableInLineShortcodes: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-L742QKS8S4

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: resume
      name: Resume
      title: Resume Viewer
      url: "/resume"
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jaysqvl"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicons/fav-256x256.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor:
    secondaryTextColor:
    backgroundColor: 
    secondaryBackgroundColor: 
    primaryColor: "#000000"
    secondaryColor: "#F5F5F5"

    # darkmode:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    #   primaryColor:
    #   secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Jaysqvl" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "> Hello World! My name is"
    title: "Jay Esquivel Jr."
    subtitle: "Build to learn, learn to build."
    content: "I'm a Software Engineering student based in Vancouver, BC exploring integrations of AI/ML into life! Check out my latest project which combines GPT and Langchain to respond to queries on any inputted PDFs."
    image: /images/hero.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/resume"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jaysqvl
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jaysqvl/
        # - icon: fab fa-twitter
        #   url: https://twitter.com/jaysqvl
        # - icon: fab fa-instagram
        #   url: https://www.instagram.com/jaysqvl/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.gif"
    content: |-
      Trying to make the world a better place, one tool at a time. I have a background in Computer Science, Mathematics, and Physics as well as have a strong interest in data science and machine learning. 
      
      Fast-facts about me:
        - Huge basketball fan, you'll find me in many different local leagues!
        - Anime watcher so recommend me your best shows!
        - Gamer, add me on Valorant: indivinity#diff
        - Techie, I love to tinker with all the new gadgets!
    skills:
      enable: true
      title: "Here are a some tools I've been sharpening my skills with recently:"
      items:
        - "Python"
        - "Langchain"
        - "Huggingface"
        - "JavaScript"
        - "PostgreSQL"
        - "Java"
        - "Docker"
        - "React"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Owner/Operator"
        company: "Jaysqvl Solutions"
        companyUrl: "https://jaysqvl.com"
        date: "Jan 2020 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "IT Solutions for small businesses and individuals as well as private tutoring for high school and university students in Math and Computer Science. Knowledge and skills in networking, virtualization/containerization, software development, cybersecurity, and more! Reach out to me via email or LinkedIn for business inquiries or tutoring requests."
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelors of Applied Science, Computer Science - Software Systems"
        school:
          name: "Simon Fraser University, Burnaby, BC"
          url: "https://www.sfu.ca/"
        date: "2022 - 2025"
        GPA: "3.09 out of 4.33"
        content: |-
          Relevant Course Work
            - CMPT210: Probability and Computing | Grade: B-
            - MATH232: Applied Linear Algebra | Grade: B+
            - MSE110: Mechatronics Design I | Grade: B+
            - CMPT300: Operating Systems I | Grade: B-
            - CMPT307: Data Structures | Grade: B
            - STAT270: Probability and Statistics | Grade: B
            - CMPT371: Data Communications/Networking | Grade: TBA

          Extracurricular Activities
            - (Active) UBC CVC Cultural and Social Society Executive Member (Multiple Roles)
            - NWPlus Hackathon 2022
        # featuredLink:
        #   enable: true
        #   name: "Projects I Made at SFU"
        #   url: "https://example.com"
      - title: "Bachelor of Science, Computer Science"
        school:
          name: "University of British Columbia, Vancouver, BC"
          url: "https://www.ubc.ca/"
        date: "2020 - 2022"
        GPA: "3.33 out of 4.33"
        content: |-
          Relevant Course Work
            - DSCI100: Data Science I | Grade: A-
            - CPSC110: Computation, Programs, and Programming | Grade: A-
            - CPSC121: Models of Computation | Grade: B+
            - CPSC210: Software Construction | Grade: A-
            - CPSC213: Computer Systems | Grade: B
            - CPSC221: Algorithms and Data Structures | Grade: A-
            - CPSC322: Artificial Intelligence | Grade: B

          Extracurricular Activities
            - UBC CVC Cultural and Social Society Executive Member (Multiple Roles)
            - NWPlus Hackathon 2021
            - NWPlus Hackathon 2020
            - SustainHacks 2021
        # featuredLink:
        #   enable: true
        #   name: "Projects I Made at UBC"
        #   url: "https://example.com"
      - title: "Dogwood Diploma (High/Secondary School Diploma)"
        school: 
          name: "Burnaby North Secondary School/Templeton Secondary School"
          url: "https://north.burnabyschools.ca/"
        GPA: "4.0 out of 4.0"
        content: |-
          Achievements
            - Principal's List - 5 Years
            - Honour Roll - 5 Years
            - Basketball Team Captain - 3 Years
            - Athlete of the Year - Grade 12
            - 2019 and 2020 Advanced Placement Scholar with Honor

          Extracurricular Activities
          
          - Student Lead Clubs: 
            - VikingsDev Coding Club
            - The Noble Tutors Club
            - Leos Leadership Club
          - School Organized Associations
            - Mini School Honours Program & Mini School Student Council
            - Student Council
            - Athletics Council

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievment.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievment.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    title: "Some Projects"
    items:
      - title: CartCompass
        content: This is a website/chrome-extension that aims to enhance your item comparison/shopping experience. Never buy the wrong brand/product again!
        image: /images/projects/compass.jpg
        badges: 
          - "HTML"
          - "CSS"
          - "JavaScript"
          - "Node"
          - "Express"
          - "React"
          - "MongoDB"
          - "Google Sheets API"
          - "Chrome API"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/cartcompass
      - title: This Hugo Website!
        content: This website was built using Hugo and the hugo-profile theme!
        image: /images/projects/websitelight.jpg
        badges: 
          - "Hugo"
          - "GitHub Actions"
          - "GitHub Pages"
          - "HTML"
          - "CSS"
          - "JavaScript"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/jaysqvl.com-source
      - title: Impersonator
        content: Query any inputted text/PDFs by attaching them to any LLM!
        image: /images/projects/impersonator.jpg
        featured:
          name: Demo
          link: https://github.com/jaysqvl/impersonator
        badges:
          - "Python"
          - "Docker"
          - "OpenAI"
          - "Langchain"
          - "HuggingFace"
          - "Streamlit"
          - "Supabase VDB"
          - "Pinecone VDB"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/impersonator

      - title: Hercules
        content: Gamified Health and Fitness App written in Java for Android
        image: /images/projects/hercules.jpg
        featured:
          name: Demo
          link: https://www.youtube.com/watch?v=h7hHna3sPq8&ab_channel=NafisAhsan
        badges:
          - "Java"
          - "Android"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/hercules

      - title: Divide and Conquer Socket Programming Game
        content: Server and Client application that uses sockets to communicate locally over a LAN
        image: /images/projects/dac.jpg
        featured:
          name: Demo
          link: https://drive.google.com/file/d/1V-U8bwtCIGmnlPYW5cCZNUvsP1jTNSAc/view
        badges:
          - "Java"
          - "Java Swing"
          - "Sockets"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/divide-and-conquer-socket-program
      
      - title: Decode Backend (SustainHacks 2nd Place)
        content: The back-end REST Api for Decode, the shopping sustainability Chrome Extension/Website
        image: /images/projects/decode.gif
        featured:
          name: Demo
          link: https://www.youtube.com/watch?v=ZcLToAFm-wI&ab_channel=ShayHayashi
        badges:
          - "Python"
          - "Flask"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/decode-backend

      - title: peerAdvice
        content: Prototype UBC Student-Lead Advising Alternative
        image: /images/projects/peeradvice.gif
        featured:
          name: Demo
          link: https://www.youtube.com/watch?v=_7WZNNuexCQ&ab_channel=JayEsquivel
        badges:
          - "HTML"
          - "CSS"
          - "JavaScript"
          - "Python"
          - "Flask"
          - "PostgreSQL"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/peeradvice
  
      - title: UBC Course Getter
        content: "A command-line webscraping tool for UBC students that circumvents bot detection to automatically enroll you in classes!"
        image: /images/projects/ubccoursegetter.jpg
        badges:
          - "Python"
          - "Docker"
          - "AWS"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/get-me-in-a-course

      - title: Unclutter Your Life
        content: Robust to do list project application written in Java created with JUnit test and other SWE design principles
        image: /images/projects/unclutter.gif
        featured:
          name: Demo
          link: https://github.com/jaysqvl/unclutter
        badges:
          - "Java"
          - "JUnit"
          - "Java Swing"
          - "GitHub Actions"
        links:
          - icon: fab fa-github
            url: https://github.com/jaysqvl/unclutter

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: jaysqvl@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Jay Esquivel Jr."
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
